name: langfuse

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # Publish semver tags as releases.
    tags: ["v*.*.*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  ORGANIZATION: meganote
  TAG: latest

jobs:
  langfuse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push clickhouse image
        id: clickhouse
        uses: docker/build-push-action@v5
        with:
          context: ./langfuse
          file: ./langfuse/clickhouse.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/clickhouse:25.2.1-debian-12-r0

      - name: Build and push langfuse-worker image
        id: clickhoulangfuse-workerse
        uses: docker/build-push-action@v5
        with:
          context: ./langfuse
          file: ./langfuse/langfuse-worker.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/langfuse-worker:3.146.0

      - name: Build and push langfuse image
        id: langfuse
        uses: docker/build-push-action@v5
        with:
          context: ./langfuse
          file: ./langfuse/langfuse.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/langfuse:3.146.0

      - name: Build and push minio image
        id: minio
        uses: docker/build-push-action@v5
        with:
          context: ./langfuse
          file: ./langfuse/minio.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/minio:2024.12.18-debian-12-r1

      - name: Build and push postgresql image
        id: postgresql
        uses: docker/build-push-action@v5
        with:
          context: ./langfuse
          file: ./langfuse/postgresql.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/postgresql:17.3.0-debian-12-r1

      - name: Build and push valkey image
        id: valkey
        uses: docker/build-push-action@v5
        with:
          context: ./langfuse
          file: ./langfuse/valkey.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/valkey:8.0.2-debian-12-r2

      - name: Build and push zookeeper image
        id: zookeeper
        uses: docker/build-push-action@v5
        with:
          context: ./langfuse
          file: ./langfuse/zookeeper.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/zookeeper:3.9.3-debian-12-r8
